### ISSUE TITLE
zeptocore: allow changing the samples with one hand

### ISSUE THREAD

**Issue by schollz** [schollz/_core#400]

**Comment by itchyjazz** [comment]
i kind of like how the pikocore works where you can change the sample with just one knob, with one hand, without having to press another button while turning a knob.

**Comment by schollz** [comment]
@itchyjazz this is introduced in v2.8! it is not enabled by default, but you can enable it by using the tool, clicking settings, and toggling "Knob X switches samples" to "on":

![image](https://github.com/schollz/_core/assets/6550035/81952bee-cfc6-4396-b566-f001d1eccf02)

**Comment by itchyjazz** [comment]
omg thank you!so excited for this.oh btw, im having trouble with putting in my own samples with the tool. i’ve followed the instructions. but it’s still not showing up on the device.i also tried it with the pikocore samples, which i downloaded from the site. when i tried loading all the pikocore samples, it said it was too big. weird. i tried one folder, it said it still was too big.pls help 🙏🏼Sent from my Trapper KeeperOn Jun 4, 2024, at 4:15 AM, Zack ***@***.***> wrote:﻿
@itchyjazz this is introduced in v2.8! it is not enabled by default, but you can enable it by using the tool, clicking settings, and toggling "Knob X switches samples" to "on":
image.png (view on web)

**Comment by itchyjazz** [comment]
im just using the one it came withSent from my Trapper KeeperOn Jun 5, 2024, at 12:13 AM, Zack ***@***.***> wrote:﻿
what is your sd card? does it have enough space?

**Comment by schollz** [comment]
@itchyjazz the sd card I supplied has enough space. can you email me a screenshot of the issue? zack@infinitedigits.co

**Comment by itchyjazz** [comment]
okif you have other instructions for loading samples onto the zeptocore, pls send me. i think i might be doing something wrong.Sent from my Trapper KeeperOn Jun 5, 2024, at 11:47 AM, Zack ***@***.***> wrote:﻿
@itchyjazz the sd card I supplied has enough space. can you email me a screenshot of the issue? ***@***.***
