### ISSUE TITLE
ectocore: Mult button should divide down after one second of holding, not after releasing button

### ISSUE THREAD

**Issue by Izaakthegreat** [schollz/_core#443]
I'm noticing that the division doesn't change until you release the hold button when dividing down, I'd like it to change instantly after holding for a certain amount of time (i.e. hold for 1 second and division changes without you releasing the button)

**Comment by schollz** [comment]
@Izaakthegreat what is the behavior if you hold down the button for 3 seconds?

**Comment by Izaakthegreat** [comment]
It would go down three divisions, one division at a time. So if it starts at /1, then holding the button would go down to /2 after one second, own to /4 after another second, then down to /8 after another second, etc. (not with those exact divisions but you get the idea). Once it hits it's lowest division it would no longer go down when holding, only go up with a press.

**Comment by schollz** [comment]
got it, done!
