### ISSUE TITLE
zeptocore web app

### ISSUE THREAD

**Issue by mrglennjones** [schollz/_core#466]
hi mate, im trying to compile a new set of samples using the online tool...

every time i am clicking download at the bottom of the page, it changes to 'processing' then the browser is randomly refreshing which is breaking the process, this seems to be the same in firefox and chrome.

so im stuck in a loop... 

`Download .zip to load onto SD card (961.31 MB)`

**Comment by schollz** [comment]
thanks for the bug report. could you email me zack@infinitedigits.co with the name of the collection? (The url at the top of the screen). I can check to see if something wonky is happening with the samples

**Comment by mrglennjones** [comment]
it appears to also refresh the browser when just idle.

**Comment by schollz** [comment]
ahh yeah the random refresh is because when I make a change to the codebase it will reload the website for everyone. it should only happen rarely - but let me know if you are seeing it happen constantly

**Comment by mrglennjones** [comment]
it happens quite often tbf
