### ISSUE TITLE
ectocore: Amen knob LED display change to make counting easier

### ISSUE THREAD

**Issue by Izaakthegreat** [schollz/_core#485]
The idea would be that when you turn up the Amen knob, instead of the LED display just turning up, it would display evenly spaced dots (starting from the center) to show how many steps it was looping through. Makes it easier to get to 2/4/8/16 steps precisely.

**Comment by Izaakthegreat** [comment]
Ah shit I have realized this is derivative with the other issue opened sorry! Should I delete?

**Comment by schollz** [comment]
added in https://github.com/schollz/_core/pull/495
