### ISSUE TITLE
ectocore: Change Amen small knob behaviour when CV is present

### ISSUE THREAD

**Issue by Izaakthegreat** [schollz/_core#500]
The Amen small knob (attenurandomizer) should act as an attenuator over the incoming CV when there is no CV present. So for instance, the when CV is plugged in and the knob is centred, there should be no CV (0V). As you go clockwise, the CV's level should increase until it is at it's full level all the way clockwise. On the other half of the knob, the CV should control how much of the randomization should be applied to the sample, with the overall level of randomization being controlled by the knob. See the [Mutable Beads Manual](https://pichenettes.github.io/mutable-instruments-documentation/modules/beads/manual/) for details of how I think this hould work, on the section where she discusses the Attenurandomizers.

**Comment by schollz** [comment]
fixed in v3.0.0
