### ISSUE TITLE
ectocore: lots of clicking & drop outs

### ISSUE THREAD

**Issue by gotascii** [schollz/_core#560]
Hi there!

Love the ectocore form factor and I can tell there's a really fun device underneath all the clicking and digital stuttering, would love to try and see if I can figure out what's up with mine. When it is operating somewhat normally I am getting a lot of clicking that kinda sounds like some sort of buffer issue. I thought maybe it was volume related but tuning everything down doesn't really seem to help. I'm on the latest firmware as of today. Not really sure how to troubleshoot, but happy to try any ideas.

**Comment by schollz** [comment]
can you send me an email: zack@infinitedigits.co 

please send a picture of the sd card

**Comment by gotascii** [comment]
Ah, ya know what slow sd card reads crossed my mind earlier. Testing w a faster card greatly improved things. I'll follow up w an email just now. Thanks!

**Comment by schollz** [comment]
great @gotascii - do let me know if you find the cards aren't working. I'd recommend a 64gb if you can, I tried some 128gb and they still had glitches whereas the right 64gb never do.

**Comment by schollz** [comment]
(also if you find a card that works really well, please let me know and I will add it to the list!)
