### ISSUE TITLE
Not fully open source, or I can't agitate enough brain cells to find source

### ISSUE THREAD

**Issue by SoLongSidekick** [schollz/_core#575]
Hiya,

I love my Zepto and have always wanted to combine it with a few other open source instruments I've bought over the years into one super desk panel that is super cool and awesome. Anyways, I gathered up all the PCB files I need for the other projects and have them connected somewhat tenuous but I can't find the files anywhere. I was going to just recreate it using the schematic but thought 1) it would be so much easier to just attach my entire Zepto to the thing instead of having to remake it's main board, and 2) it's at least worth reaching out about. Did I just miss them or was there an oversight?

Thanks,
Blake

**Comment by schollz** [comment]
hi Blake - gerbers are not out yet. waiting to recoup the costs of the r&d to release them.

**Comment by SoLongSidekick** [comment]
Any chance you'd be willing to send them to me with a "not duplicatable more than once, non-commercial" type of license? I have no interest in trying to make money on your design, but would be more than happy to provide any insights I gain from CNC'ing my personal abomination back to the project. Actually, since I'm planning on CNCing mine if it would make you more comfortable I could get by with just a DXF/SVG vector image of the PCB. That way I wouldn't have the gerbers or any way to convert them into  gerbers that isn't any easier than manually reproducing them from the schematic (although I would prefer the gerbers, but hey beggars can't be choosers). If you're still not comfortable with it no worries it's your design. Part of what I'm working on personally is developing a way of producing 90% fab house quality PCBs at home, by CNCing the copper clad, then applying UV curing solder mask (black is my preference), throwing the PCB either under my laser engraver or onto my resin printer screen (second one probably sounds weird but I was able to produce pretty excellent boards out of presensitized copper clad and having the printer's screen just display an image of the mask for ~4 min) to perfectly remove the areas of the solder mask we don't want to stay (around pads, etc.), then creating silk screens by curing the screen ink onto the screen with the laser engraver, and silk screening the boards. They come out pretty amazing and I'm still not done fine tuning; the only thing I haven't put the money into figuring out is if I can electroplate the boards with gold as that's by far my favorite look for PCBs. All this just because I want a panel on my desk that allows me to control my smart home crap and also has some funky music making gear baked in. Geez...

Anyways, my point is it might be cool someday if with the insights I glean you're able to offer small run "developer's edition" (or whatever) PCBs that are handmade but still look amazing. Just a thought.
