### ISSUE TITLE
zeptocore with 6.0.0 keeps rebooting 

### ISSUE THREAD

**Issue by x2db** [schollz/_core#603]
After updating to the latest version . I do see the 6.0.0 indicated properly but then the sequencer starts and when it gets to step 8 it waits and reboots.
Is there way to retrieve/download the latest previous version 5.0.11?
thank you

**Comment by schollz** [comment]
hi @x2db - to answers your question, yes. you can download htis: https://github.com/schollz/_core/releases/download/v5.0.11/zeptocore_v5.0.11.uf2

to address your issue - are you loading from a previous save or anything? I wonder if that could be an issue. also does it work if you use usb power?

**Comment by x2db** [comment]
Zack, so I uploaded and upgraded to V6.01 and the issue is is different. I did manage to save to the  location one which is the default when the machine starts. So I get more than 6 steps now. I think there is some other bigger issue. Whenever I select any other location that has been saved with 5.0x it crashes the machine... I didn't not update all the times so I could have "safe format" that was as of 5.01 or so. You might have updated the save format thus crashing with older savefilesxx. So no way to to load anything that I've saved with 5.0x. . Effectively rendering all my saves from previous version useless. I'm attaching a few save files for your to test ... of course I have 15 banks so the "saves" will complain about missing sample banks ... In either case the never firmware version and or missing banks should no freeze the load procedure. D+B. So you should count that ppl will not go trough all the upgrades b/c most of them are related to the eurorack module that I'm asking to buy :) So please make sure that never versions will not crash loading older savefiles. If there is way for me to downgrade to 5.0x and re-save the presets so than I can safely upgrade to 6.0x please let me know

**Comment by x2db** [comment]
Zack, 

If you cannot retrieve some of my save files from GitHub I’m attaching them here 
Let me know if you need any other info from me 

Regards
George 


here is a snap of the card,, from here you can see I cannot attach the whole thing to an email

**Comment by schollz** [comment]
Hi George!

Sorry, I should have written this but the major change (v5 -> v6) represents a breaking change, so the save files won't work on v6 when they were created for v5. For zeptocore there are ver new features in v6 (v6 is mostly to get ready for the ectocore) so you can still use your save files by installing the v5.X.Y firmwares. I will make an issue for transitioning save files so that it can be done in the future.
