### ISSUE TITLE
some effects works as toggles and some are momentary 

### ISSUE THREAD

**Issue by x2db** [schollz/_core#630]
Is there a new feature I don't know about that I can have some effects working as toggle and some momentary ? Or is it a bug. I wish all effects were momentary. As I mentioned earlier I do work with lover BPMs and that is where momentary and or shorter effect "gates" make a lot more sense. Love this product !

**Comment by x2db** [comment]
Zack

Oh.. Sorry missunderstanding ?  yeah I upgraded but now all effects are Toggle only. I needed the opposite. Now you force me to double click if I need only short burst of effects. Am I missing something … is there setting to make them all momentary? … Otherwise I will go back to 5.x and be stuck there :(

Thanks 
George

**Comment by schollz** [comment]
hi George,

the effects have always been toggle. there was a bug where they would immediately turn off. 
there is no setting to make them momentary at the momentary at the moment! but I just made an issue where I'll work on a pull request to add it: https://github.com/schollz/_core/issues/648

best,
Zack

**Comment by x2db** [comment]
Zack,

Thanks thanks!
I had the same with JDXI (Roland) … one of the updates  supposedly  “fixed bug” that I used as a feature … so I’ve never upgraded to 4.x 

First I though that if I'd use the Jump Mode the effects would work as momentary.  

As I mentioned elsewhere, I rarely use effects on the whole step length. So momentary is vital …
I will wait till day you put it to a future release up until then I need to do two clicks for each effect played live. With higher BPM I really need to do some workout on my fingers :)

Thanks 
George

**Comment by schollz** [comment]
Lol! Agreed that some bugs become features....

But this bug will be a feature really soon!! Maybe even today 😁

**Comment by schollz** [comment]
@x2db, here it is: https://zeptocore.com/#momentary-fx-mode, try it in v6.0.9 (note that you <v6 saves will not work, you should delete them before upgrading): https://github.com/schollz/_core/releases/download/v6.0.9/zeptocore_v6.0.9.uf2
