### ISSUE TITLE
v6.2.0 SD Card error while booting

### ISSUE THREAD

**Issue by DieKonkurrenz** [schollz/_core#659]
Hi! :) 
I just essembled the unit and got it double checked by an electrician. I want to boot it but it just shows SD-card even though I inserted the one that came with the thonk kit (kexin 16 gb). Did I make a mistake while soldering? 
Have a good one!

**Comment by schollz** [comment]
Did you load any samples onto the card?

**Comment by DieKonkurrenz** [comment]
Ahh shit i thought it would come with a samplepack on it. :D I'll check. Thanks for the fast answer.

**Comment by schollz** [comment]
It should have

**Comment by DieKonkurrenz** [comment]
Jup it has samples on it

**Comment by schollz** [comment]
Then it must be soldering. email me your order number and a picture of the soldering top and bottom

zack@infinitedigits.co
